### ISSUE TITLE
401 - Unauthorised 

### ISSUE THREAD

**Issue by jpguttione** [vtex-apps/wordpress-integration#22]
**Describe the bug**
The client has complained about the error after some changes in the blog post text.
After that we're receiving 401 from GraphQL.
Is that some integration problem? Is the component covering all features that a wordpress post can have?
I've noticed before that if a post doesn't have a featured image, the page of the full detailed post crashes.
But in the current scenario we have the featured image on the post.

**To Reproduce**

1. Go to https://bennemann.myvtex.com/blog

**Expected behavior**
Expected the list of posts and the post itself to be rendered.

**Screenshots**
<img width="1506" alt="Screen Shot 2020-03-24 at 13 55 09" src="https://user-images.githubusercontent.com/53085698/77454445-4f0efd00-6dd7-11ea-8ab6-c3e80d03e842.png">
<img width="794" alt="Screen Shot 2020-03-24 at 13 56 29" src="https://user-images.githubusercontent.com/53085698/77454449-50402a00-6dd7-11ea-8eeb-350029f9adc2.png">

**Comment by rsantiago88** [comment]
Hello Guys,

Any update on this issue ?

Thank you !

**Comment by polishq** [comment]
Fixed by this PR: https://github.com/vtex-apps/wordpress-integration/pull/28

**Comment by jpgutti** [comment]
@polishq Was the issue solved?
