### ISSUE TITLE
Example usage / Documentation update

### ISSUE THREAD

**Issue by doruradu** [vtex-apps/wordpress-integration#32]
**What are you trying to accomplish? Please describe.**

Hi! I'm trying to use the wordpress integration app so I can display some blogposts on the store home.

**What have you tried so far?**
Installed the app (wordpress-integration), add it as a dependency in the manifest, defined the routes, configured it in the admin. When I tried to link the files, I get this error:

`21:40:13.769 - error: App build failed with message: I couldn't find a block "sanovita.store-theme@0.x:store.blog-home". You need to declare the block or have your app depended on another app that declares it. This error may be caused by a change in behavior resolving blocks from indirect app dependencies. Further info here: https://vtex.io/docs/releases/2019-12-12/declaring-blocks-stemming-from-indirect-dependencies..  

21:40:13.776 - error: I couldn't find a block "sanovita.store-theme@0.x:store.blog-home". You need to declare the block or have your app depended on another app that declares it. This error may be caused by a change in behavior resolving blocks from indirect app dependencies. Further info here: https://vtex.io/docs/releases/2019-12-12/declaring-blocks-stemming-from-indirect-dependencies.. vtex.builder-hub@0.248.2  `

The link stated in the error is dead and the documentation seems incomplete. Can you help, please?

**Additional info**

![image](https://user-images.githubusercontent.com/42587916/82157035-b8ffcc00-9887-11ea-8506-ba822d780d47.png)

![image](https://user-images.githubusercontent.com/42587916/82157044-c74de800-9887-11ea-8bd9-a6303aba9728.png)

![image](https://user-images.githubusercontent.com/42587916/82157055-d9c82180-9887-11ea-9a58-0e09de51bb36.png)

| Account        | Workspace        |
| -------------- | ---------------- |
| `sanovita` | `beta` |

**Comment by luiscvz** [comment]
Hi @doruradu I have the same issue, how could you solve it?
Thanks!

**Comment by SaraMmejia** [comment]
I have the same problem
