### ISSUE TITLE
Content links without any classes, impossible to access them

### ISSUE THREAD

**Issue by brunocampestrini-acct** [vtex-apps/wordpress-integration#70]
**Describe the bug**
On the link tags from the wordpress content, it is impossible to access them via CSS, they're still that annoying standard blue. Is there a way to convert this anchor tags in helpers? This started to happen in the 2.x version of builder styles.

**To Reproduce**
Build the application within the builder styles version 2.x

**Expected behavior**
Render helper classes on content elements, such as anchors

**Screenshots**
![image](https://user-images.githubusercontent.com/69987917/116601479-f0348500-a900-11eb-8400-5f7a8ac3b928.png)

**Comment by brunocampestrini-acct** [comment]
Any news?

**Comment by SDBowen** [comment]
Hi @brunocampestrini-acct 

The latest release included a CSS handle, `postCategoryLink`, that will let you target the Category link text.

For links that are in the blog content itself, any classes that are present in the blog content are carried over by the Wordpress app.

Does this solution work for you?

**Comment by brunocampestrini-acct** [comment]
@SDBowen 
we're already using this handle here, but does not work, I'm referring to the anchor tag from the body html, it is pulled among the posts data. For us it's not viable to add classes in wordpress before importing to this integration, we need an automatic way to access these elements without classes, despite Vtex does not allow to do that anymore. 
![image](https://user-images.githubusercontent.com/69987917/118852580-487bf880-b8a9-11eb-8585-0b30de484f07.png)

**Comment by SDBowen** [comment]
I see. The team is in the middle of our current sprint. Next week we will select which tasks to tackle.

This work will likely get addressed then, I will follow up in this issue.
