### ISSUE TITLE
Graphql Error 500

### ISSUE THREAD

**Issue by doruradu** [vtex-apps/wordpress-integration#72]
**Describe the bug**
Error: GraphQL error: Request failed with status code 500 when retrieving latest posts.

**To Reproduce**

1. Go to https://wordpress--fstudio.myvtex.com/
2. Scroll to the bottom of the page
3. See error

**Expected behavior**
Show the latest blog posts

**Screenshots**

**Desktop environment:**
Not specific to browser

**Smartphone environment:**

Not specific to browser

**Additional context**
I think it's something related to a special character that is present in the blog. If I change the blog from the admin and instead of blog.f64.ro I put blog.dacris.net (or any other blog), the articles appear.

**Comment by SDBowen** [comment]
Hi @doruradu 

You are right, It does seem to be an issue with a special character.

I see this returned in the headers from the WordPress API:

```
x-wp-doingitwrong: register_rest_route (din 5.5.0; DefiniÈ›ia rutei REST API pentru <code>pais-feeds/v1/posts</code> nu cuprinde argumentul <code>permission_callback</code>, care este necesar. Pentru rutele REST API care sunt destinate sÄƒ fie publice, foloseÈ™te <code>__return_true</code> ca un apel-Ã®napoi pentru permisiuni.)
```
From the response headers [of this query](https://blog.f64.ro/wp-json/wp/v2/posts?page=1&per_page=4&status=publish)

Which is causing this 500 error:
`message: 'Invalid non-ASCII or control character in header: 0x00C8'`

Are you able to clear this error on the WordPress installation?

**Comment by doruradu** [comment]
Hi @SDBowen !

Thanks for the reply  👍  We fixed it from the wordpress installation.
