### ISSUE TITLE
Is possible get the custom post created?

### ISSUE THREAD

**Issue by jesusuzcategui** [vtex-apps/wordpress-integration#96]
Hi, I have learned how to integrate WordPress and vtex. I want know if exist a way to get data of custom post created, for example, elements of a type content named projects and his custom fields. Only I make two pages:

1) https://jdevwordpress--titamedia.myvtex.com/blog
2) https://jdevwordpress--titamedia.myvtex.com/blog/post/hello-world

| Account        | Workspace        |
| -------------- | ---------------- |
| `titamedia` | `jdevwordpress` |

**Comment by polishq** [comment]
Hi @jesusuzcategui, no, this is not possible with the current version of the app. The app supports the standard WordPress Post and Page content types only. If you require the ability to render custom content types, I recommend developing a custom version of the app specific to your client's needs.
